version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8001}:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - CONFIG_PATH=/app/config/config.json
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./downloads:/app/downloads
      - ./config.json:/app/config/config.json

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6380}:6379"
